version: "3"

services:
  httpd:
    image: nginx:alpine
    volumes:
      - html:/usr/share/nginx/html:ro
    restart: always
    ports:
    - "80:80"

  app:
    build: .
    image: netresearch/jira-export
    volumes:
      - html:/opt/jira-export/www

  build:
    build: ./build/
    volumes:
      - .:/srv/www

volumes:
  html: